name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Compile and Test the Java Application
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Unit Tests
      run: mvn clean test

  # Job 2: Build and Ship the Docker Image
  build-image:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    # New Step: Log into Docker Hub using our secure secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Upgraded Step: Build AND Push the image to the cloud warehouse
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        # Replace YOUR_DOCKERHUB_USERNAME with your actual username below
        tags: |
          andyhatt/resilient-ping:latest
          andyhatt/resilient-ping:${{ github.sha }}